"""Make username non-unique

Revision ID: 0309db1e86c0
Revises: fc78dcef5f42
Create Date: 2025-01-15 16:16:19.431269

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0309db1e86c0"
down_revision = "fc78dcef5f42"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("user_username_key", type_="unique")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint("user_username_key", ["username"])

    # ### end Alembic commands ###
