"""Add auth0 id

Revision ID: fc78dcef5f42
Revises: de00b5a84172
Create Date: 2025-01-06 14:44:42.412604

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fc78dcef5f42"
down_revision = "de00b5a84172"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("auth0_id", sa.String(), nullable=False))
        batch_op.create_unique_constraint(None, ["auth0_id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")
        batch_op.drop_column("auth0_id")

    # ### end Alembic commands ###
